export const sectors = [
  { id: 'financeiro', name: 'Financeiro', description: 'Boletos, pagamentos e negociações' },
  { id: 'eventos', name: 'Eventos', description: 'Abertura e acompanhamento de eventos' },
  { id: 'rastreamento', name: 'Rastreamento', description: 'Instalação, manutenção e orientações' },
  { id: 'cadastro', name: 'Cadastro', description: 'Dados cadastrais e proteção' },
  { id: 'assistencia', name: 'Assistência 24h', description: 'Orientações e direcionamento' },
  { id: 'outros', name: 'Outros assuntos', description: 'Fale com nossa equipe' },
];

export const initialTickets = [
  {
    id: 'GPV-260925-1048',
    customer: 'João Henrique',
    initials: 'JH',
    sector: 'Financeiro',
    status: 'waiting',
    wait: '01:32',
    origin: 'Site',
    phone: '(81) 9 9999-1020',
    vehicle: 'Fiat Strada 2024',
    plate: 'ABC1D23',
    messages: [
      { id: 1, from: 'customer', text: 'Olá, preciso verificar uma cobrança no meu boleto.', time: '11:21' },
      { id: 2, from: 'system', text: 'Atendimento encaminhado para Financeiro.', time: '11:21' },
    ],
  },
  {
    id: 'GPV-260925-1049',
    customer: 'Maria Eduarda',
    initials: 'ME',
    sector: 'Rastreamento',
    status: 'waiting',
    wait: '03:10',
    origin: 'WhatsApp',
    phone: '(81) 9 8888-2211',
    vehicle: 'Honda CG 160',
    plate: 'QYZ9E71',
    messages: [
      { id: 1, from: 'customer', text: 'Meu rastreador está sem atualizar desde cedo.', time: '11:19' },
    ],
  },
  {
    id: 'GPV-260925-1050',
    customer: 'Carlos José',
    initials: 'CJ',
    sector: 'Eventos',
    status: 'waiting',
    wait: '04:28',
    origin: 'Site',
    phone: '(81) 9 7777-3030',
    vehicle: 'Chevrolet Onix 2023',
    plate: 'RZT4B19',
    messages: [
      { id: 1, from: 'customer', text: 'Preciso saber quais documentos devo enviar para abrir um evento.', time: '11:18' },
    ],
  },
  {
    id: 'GPV-260925-1042',
    customer: 'Paulo Fernando',
    initials: 'PF',
    sector: 'Cadastro',
    status: 'active',
    wait: '08:12',
    origin: 'WhatsApp',
    phone: '(81) 9 6666-4410',
    vehicle: 'Fiat Strada',
    plate: 'PEA2F77',
    messages: [
      { id: 1, from: 'agent', text: 'Olá, Paulo! Sou Pedro e vou continuar seu atendimento por aqui.', time: '11:09' },
      { id: 2, from: 'customer', text: 'Perfeito. Quero atualizar meu telefone de contato.', time: '11:10' },
    ],
  },
];
